### PR TITLE
add argument parsing to Android_Waydroid_Cage.sh

### PR DESCRIPTION
**Pull request by Alistair1231**
Hi, thanks for sharing your work!
I added argument parsing to Android_Waydroid_Cage.sh:

```
Usage: ./Android_Waydroid_Cage.sh [OPTIONS]
Options:
  -h, --help        Show this help message
  -m, --mode        Set the mode (default: 1280x800@60Hz)
  -p, --package     Specify the package to launch
```
With this change, you can run this e.g. `./Android_Waydroid_Cage.sh -p "com.google.android.youtube" -m "1920x1080@60Hz"`
This makes adding custom shortcuts to steam easier, especially when trying to support multiple resolutions.

I also changed the heredoc to be quoted, so the content doesn't have to be escaped. (i.e. "EOF" instead of EOF)

### CODE REVIEW

**Comment by ryanrudolfoba** [comment]
i'll test this later today before i do some overhaul to support Android 13 images in the future.

**Comment by mrvictory1** [comment]
> i'll test this later today before i do some overhaul to support Android 13 images in the future.

can you boot any games on Android 13? afaik libndk crashes on Android 13 when loading anything 3D and libhoudini doesn't even initialize.

**Comment by ryanrudolfoba** [comment]
> > i'll test this later today before i do some overhaul to support Android 13 images in the future.
> 
> can you boot any games on Android 13? afaik libndk crashes on Android 13 when loading anything 3D and libhoudini doesn't even initialize.

Its a mixed bag for me some games work like Roblox as it has x86 apk. Clash of Clans work also maybe it uses x86 apk.

LIBNDK installs fine on A13, while LIBHOUDINI doesnt as the waydroid_script doesnt have it - although its there but the script has it commented. I haven't tried uncommenting for A13 LIBHOUDINI.

I've commented here for any ideas how to troubleshoot A13 LIBNDK-

https://github.com/Benjamin-Loison/waydroid/issues/16#issuecomment-2433532914

My next plan is to build A13 image on my own and see if it has same behavior wIth LIBNDK.

**Comment by ryanrudolfoba** [comment]
This breaks APKs added to Game Mode.

**Pull request closed without merging**
